set(CMAKE_SYSTEM_NAME Generic)

set(TOOLCHAIN_PREFIX arm-none-eabi-)

set(CMAKE_LINKER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_EXE_LINKER_FLAGS "-nostdlib -nostartfiles -nodefaultlibs -static")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}as)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)

set(COMMON_COMPILER_FLAGS "-mcpu=${ARM_NONE_EABI_MCPU_FLAG}")
set(CMAKE_ASM_FLAGS ${COMMON_COMPILER_FLAGS})
set(CMAKE_C_FLAGS "${COMMON_COMPILER_FLAGS} -ffreestanding -nostdlib -Wall -Wextra -fno-builtin")

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy)