set(CMAKE_SYSTEM_NAME Generic)

set(TOOLCHAIN_PREFIX arm-none-eabi-)

set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}as)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)

set(COMMON_COMPILER_FLAGS "-mcpu=${MCPU_FLAG} -ffreestanding")
#set(CMAKE_ASM_FLAGS ${COMMON_COMPILER_FLAGS})
set(CMAKE_C_FLAGS "${COMMON_COMPILER_FLAGS} -nostdlib -O2 -Wall -Wextra")

set(CMAKE_EXECUTABLE_SUFFIX ".elf")